package de.neone.simbroker.ui.theme
import androidx.compose.ui.graphics.Color

val topBarColorLight = Color(0xFFC4D7EE)
val bottomBarColorLight = Color(0xFFE7F0F9)
//val bottomBarColorLight = Color(0xFFC2D7ED)

val topBarColorDark = Color(0xFF4779A0)
val bottomBarColorDark = Color(0xFF112B48)
//val bottomBarColorDark = Color(0xFF13365D)

val colorUp = Color(0xFF4ABB36)
val colorDown = Color(0xFFF31D1D)

val buy = Color(0xFF1B8614)
val sell = Color(0xFF831313)

val chartLight = Color(0xFF0074D0)
val chartDark = Color(0xFF0099FF)
//val chartDark = Color(0xFFF700FF)

val isFavoriteColor = Color(0xFFFFEB3B)
val coinColor = Color(0xFFEECE68)
//val coinColor = Color(0xFF6FCFFD)

val primaryLightMediumContrast = Color(0xFF144E82)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF3D719B)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF293845)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF5F6F7E)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF00395D)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF41719C)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF7F9FF)
val onBackgroundLightMediumContrast = Color(0xFF181C20)
val surfaceLightMediumContrast = Color(0xFFF7F9FF)
val onSurfaceLightMediumContrast = Color(0xFF0E1215)
val surfaceVariantLightMediumContrast = Color(0xFFDEE3EB)
val onSurfaceVariantLightMediumContrast = Color(0xFF223C54) // Navigation Icons
val outlineLightMediumContrast = Color(0xFF4D5359)
val outlineVariantLightMediumContrast = Color(0xFF686E74)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2D3135)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEEF1F6)
val inversePrimaryLightMediumContrast = Color(0xFF99CCFA)
val surfaceDimLightMediumContrast = Color(0xFFC4C7CC)
val surfaceBrightLightMediumContrast = Color(0xFFF7F9FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF1F4F9)
val surfaceContainerLightMediumContrast = Color(0xFFE6E8EE)
val surfaceContainerHighLightMediumContrast = Color(0xFFDADDE2)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCFD2D7)

val primaryDark = Color(0xFF8EBADB)
val onPrimaryDark = Color(0xFF003351)
val primaryContainerDark = Color(0xFF074B72)
val onPrimaryContainerDark = Color(0xFFCCE5FF)
val secondaryDark = Color(0xFFB8C8DA)
val onSecondaryDark = Color(0xFF23323F)
val secondaryContainerDark = Color(0xFF394857)
val onSecondaryContainerDark = Color(0xFFD4E4F6)
val tertiaryDark = Color(0xFF9CCBFB)
val onTertiaryDark = Color(0xFF003354)
val tertiaryContainerDark = Color(0xFF124A73)
val onTertiaryContainerDark = Color(0xFFCFE5FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101418)
val onBackgroundDark = Color(0xFFE0E2E8)
val surfaceDark = Color(0xFF101418)
val onSurfaceDark = Color(0xFFE0E2E8)
val surfaceVariantDark = Color(0xFF42474E)
val onSurfaceVariantDark = Color(0xFFE8ECEF)  // Navigation Icons
val outlineDark = Color(0xFF8C9198)
val outlineVariantDark = Color(0xFF42474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E2E8)
val inverseOnSurfaceDark = Color(0xFF2D3135)
val inversePrimaryDark = Color(0xFF2C638B)
val surfaceDimDark = Color(0xFF101418)
val surfaceBrightDark = Color(0xFF36393E)
val surfaceContainerLowestDark = Color(0xFF0B0F12)
val surfaceContainerLowDark = Color(0xFF181C20)
val surfaceContainerDark = Color(0xFF1C2024)
val surfaceContainerHighDark = Color(0xFF272A2E)
val surfaceContainerHighestDark = Color(0xFF313539)